services:
  redis:
    image: redis:latest
    container_name: personal_website_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    network_mode: host
volumes:
  redis_data:
