export enum ArticleTag {
  TECH = 'tech',
  TECHNOLOGY = 'technology',
  SELFHOSTING = 'selfhosting',
  PROGRAMMING = 'programming',
  PRIVACY = 'privacy',
  DEVELOPMENT = 'development',
  VITE = 'vite',
  SVELTE = 'svelte',
  REACT = 'react',
  JAVASCRIPT = 'javascript',
  GATSBY = 'gatsby',
  SVELTEKIT = 'sveltekit',
  NEXTJS = 'nextjs',
  CSS = 'css',
  HTML = 'html',
}
